num_shot: 1
gfm_dim: 100
device: 'cuda:0'
task: 'graph'
dataset:
  name: 'COX2'
model:
  backbone: 'GCN'
  hidden_dim: 64
  num_layers: 4
  dropout: 0.7
optim:
  lr: 0.1
  wd: 0.1
  layer: 1
  test_shot: 20
  prompt_delta: 1.0
  prompt_tau: 0.2
  epochs: 500
  pre_train_epochs: 5
  pre_train_lr: 0.0001
  pre_train_wd: 0.001