dataset:
  name: PROTEINS
device: cuda:0
model:
  alpha: 0.3
  backbone: GCN
  hidden_dim: 64
  num_layers: 2
num_shot: 3
optim:
  epochs: 500
  layer: 0
  lr: 0.1
  prompt_delta: 0.5
  prompt_tau: 0.1
  pu: true
  test_shot: 3
  wd: 0.0
task: graph
