num_shot: 10
device: 'cuda:0'
dataset:
  name: 'chameleon'
model:
  hidden_dim: 256
  backbone: 'GCN'
  num_layers: 3
optim:
  lr: 0.0001
  wd: 0.1
  test_shot: 50
  prompt_delta: 0.5
  prompt_tau: 0.9
  epochs: 20