dataset:
  name: photo
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 2
num_shot: 3
optim:
  epochs: 500
  lr: 1.0e-05
  prompt_delta: 0.5
  prompt_tau: 0.1
  test_shot: 1
  wd: 0.001
