num_shot: 3
device: 'cuda:0'
dataset:
  name: 'wisconsin'
model:
  backbone: 'GCN'
  hidden_dim: 256
  num_layers: 4
optim:
  lr: 0.00001
  wd: 0.001
  test_shot: 100
  prompt_delta: 0.5
  prompt_tau: 0.7
  epochs: 200