num_shot: 5
device: 'cuda:0'
task: 'graph'
dataset:
  name: 'BZR'
model:
  backbone: 'GCN'
  hidden_dim: 128
  num_layers: 4
optim:
  lr: 0.1
  wd: 0.0001
  layer: 0
  test_shot: 50
  prompt_delta: 0.7
  prompt_tau: 0.2
  epochs: 200