num_shot: 1
gfm_dim: 100
device: 'cuda:0'
task: 'graph'
dataset:
  name: 'PROTEINS'
model:
  backbone: 'GCN'
  hidden_dim: 64
  num_layers: 2
  dropout: 0.0
optim:
  lr: 0.1
  wd: 0.01
  layer: 2
  test_shot: 3
  prompt_delta: 0.2
  prompt_tau: 0.1
  epochs: 500
  pre_train_epochs: 10
  pre_train_lr: 0.01
  pre_train_wd: 0.0001