dataset:
  name: photo
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 2
num_shot: 10
optim:
  epochs: 50
  lr: 0.01
  prompt_beta: 0.0005
  prompt_delta: 0.3
  prompt_tau: 0.5
  test_shot: 1
  wd: 0.001
