num_shot: 10
device: 'cuda:0'
dataset:
  name: 'cornell'
model:
  backbone: 'GCN'
  hidden_dim: 256
  num_layers: 3
optim:
  lr: 0.0001
  wd: 0.0001
  test_shot: 100
  prompt_delta: 0.8
  prompt_tau: 1.0
  epochs: 100