dataset:
  name: squirrel
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 3
num_shot: 1
optim:
  epochs: 10
  lr: 0.1
  prompt_delta: 0.001
  prompt_tau: 0.7
  test_shot: 5
  wd: 0.1
