dataset:
  name: cornell
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 3
num_shot: 3
optim:
  epochs: 10
  layer: 0
  lr: 1.0e-05
  prompt_delta: 0.7
  prompt_tau: 1.0
  test_shot: 100
  wd: 0.1
