dataset:
  name: wisconsin
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 4
num_shot: 5
optim:
  epochs: 500
  lr: 1.0e-05
  prompt_beta: 0.1
  prompt_delta: 1.0
  prompt_tau: 0.7
  test_shot: 1
  wd: 0.001
