dataset:
  name: chameleon
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 3
num_shot: 5
optim:
  epochs: 100
  lr: 0.01
  prompt_delta: 0.1
  prompt_tau: 0.1
  test_shot: 1
  wd: 0.001
