num_shot: 10
device: 'cuda:0'
dataset:
  name: 'squirrel'
model:
  hidden_dim: 256
  backbone: 'GCN'
  num_layers: 3
optim:
  lr: 0.01
  wd: 0.001
  test_shot: 1
  prompt_delta: 0.01
  prompt_tau: 0.2
  epochs: 10