dataset:
  name: wisconsin
device: cuda:0
model:
  backbone: GCN
  hidden_dim: 256
  num_layers: 4
num_shot: 10
optim:
  epochs: 100
  lr: 1.0e-05
  prompt_beta: 0.7
  prompt_delta: 0.0001
  prompt_tau: 0.5
  test_shot: 1
  wd: 0.1
